"""Initial tables

Revision ID: 4d4459b9d041
Revises: 
Create Date: 2026-05-06 09:08:34.763835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4459b9d041'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_product_code'), ['product_code'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('export_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_code', sa.String(length=50), nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_receipts_receipt_code'), ['receipt_code'], unique=True)

    op.create_table('import_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_code', sa.String(length=50), nullable=False),
    sa.Column('import_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_receipts_receipt_code'), ['receipt_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_import_receipts_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('import_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['import_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_details_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_details_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_details_receipt_id'), ['receipt_id'], unique=False)

    op.create_table('export_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('import_detail_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_detail_id'], ['import_details.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['export_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_details_import_detail_id'), ['import_detail_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_details_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_details_receipt_id'), ['receipt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_details_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_export_details_product_id'))
        batch_op.drop_index(batch_op.f('ix_export_details_import_detail_id'))

    op.drop_table('export_details')
    with op.batch_alter_table('import_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_details_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_import_details_product_id'))
        batch_op.drop_index(batch_op.f('ix_import_details_expiry_date'))

    op.drop_table('import_details')
    with op.batch_alter_table('import_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_receipts_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_import_receipts_receipt_code'))

    op.drop_table('import_receipts')
    with op.batch_alter_table('export_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_receipts_receipt_code'))

    op.drop_table('export_receipts')
    op.drop_table('users')
    op.drop_table('suppliers')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_code'))

    op.drop_table('products')
    # ### end Alembic commands ###
